### ISSUE TITLE
CatBoost Classifier

### ISSUE THREAD

**Issue by salsa360** [rick12000/confopt#4]
Hi Rick,

I'm trying to use your code with the CatBoost classifier but got the following error message:

**ValueError: Unable to auto-allocate evaluation metric for classifier prediction type.**

What do I do?  Below is my code:

parameter_search_space = {
    'iterations_values': [100, 200, 300],
    'depth_values': [6, 7, 8, 9],
    'learning_rate_values': [0.1, 0.05, 0.01],
}

from confopt.tuning import ConformalSearcher

searcher = ConformalSearcher(
    model=CatBoostClassifier(),
    X_train=X_train,
    y_train=y_train,
    X_val=X_Cal,
    y_val=y_cal,
    search_space=parameter_search_space,
    prediction_type="classifier",
)

searcher.search(
    runtime_budget=120  # How many seconds to run the search for
)

Attached is the error screenshot.

![Screenshot 2024-02-11 135941](https://github.com/rick12000/confopt/assets/48823169/7ed596ec-658a-47e9-a9f2-9edf1ab16f88)

Cheers 
Kush

**Comment by rick12000** [comment]
Hi Kush!

Thanks for raising. I believe you are passing an unsupported string value into the `prediction_type` input when you initialize the `ConformalSearcher` class. 

The accepted values that input can take are either "regression" or "classification" as stated in the docstring of the class; the error you received is complaining that it's unable to assign a loss function because it doesn't know what kind of prediction task this is. If you switch from "classifier" to "classification" it should work. So:

> model=CatBoostClassifier(),
> X_train=X_train,
> y_train=y_train,
> X_val=X_Cal,
> y_val=y_cal,
> search_space=parameter_search_space,
> prediction_type="classification",
> )

That said, this library was only explicitly tested on scikit-learn predictors, so let me know if you run into further issues with CatBoost and I can try to troubleshoot. (In theory the library should work with any predictor that has `.fit()` and `.predict()` method calls)

**Comment by rick12000** [comment]
Another thing I noticed. Your parameter search dictionary's keys must have the same names as the parameter you're optimizing (this follows scikit-learn's [GridSearchCV](https://www.mygreatlearning.com/blog/gridsearchcv/) convention). So for eg. instead of 'learning_rate_values' you should just have 'learning_rate', otherwise ConfOpt won't be able to match it back to CatBoost's actual inputs. Your search space dictionary should be:

> parameter_search_space = {
> 'iterations': [100, 200, 300],
> 'depth': [6, 7, 8, 9],
> 'learning_rate': [0.1, 0.05, 0.01],
> }

**Comment by salsa360** [comment]
Hi Rick,

Thanks for your prompt responses. I was in a rush and made some typo errors and re-running my script using the ExtraTreesClassifier worked fine.

Unfortunately, the CatBoost Classifier does not work and I got the following error:

"ImportError: cannot import name 'CatBoostClassifier' from 'sklearn.ensemble' (C:\Users\kushw\anaconda3\Lib\site-packages\sklearn\ensemble\__init__.py)"

This is most likely due to CatBoost not being part  of the SKLearn ensemble of algorithms.  Maybe I should have picked up on this when I ran the LazyClassifier from lazypredict.

Cheers
Kush
